### PR TITLE
add CMake option to toggle doxygen documentation

### PR DESCRIPTION
**Pull request by maddinat0r**
Yet another PR, this time with the ability to toggle creation of doxygen documentation (on by default).

By the way, keep up the good work! :+1:

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR, but what is the purpose of this option? The documentation is not generated by CMake, but only when you build the doc target which is not built by default.

**Comment by maddinat0r** [comment]
You are right, but this might (in my case) confuse people when they compile a project (which depends on cppformat), since the main project will have a target named "doc". This target however will generate cppformat documentation, not the main project's documentation.  
I could also push another commit to mark this option as advanced, so that it's invisible by default for the "normal" user (people who directly setup and compile cppformat as main project, instead of creating CMake dependencies).

**Comment by vitaut** [comment]
Fair enough. I think there is no need to mark the option advanced as the number of options is small, but I've changed the naming of this option and `FMT_TESTS` to be consistent with the names of the targets they controls, `FMT_DOC` for the doc target and `FMT_TEST` for the test target. `FMT_INSTALL` is already in this form (https://github.com/cppformat/cppformat/commit/2541dab11729c5f8be78980a7c1813226155a338). Hope you don't mind.

**Comment by maddinat0r** [comment]
Sounds logical to me. Thanks for your work! :+1:

**Pull request merged**
