### PR TITLE
Use MSVC intrinsics for better performance

### PR DESCRIPTION
**Pull request by CarterLi**
Try to fix https://github.com/cppformat/cppformat/issues/115
Not tested yet due to lacking of MSVC compiler

### CODE REVIEW

**Comment by vitaut** [comment]
Merged, thanks!

**Comment by vitaut** [comment]
Applied some changes in https://github.com/cppformat/cppformat/commit/27e0bf72c02e830d5346738e59ea9848c32c2de9 as I think the correct intrinsic to use is `_BitScanReverse`. Also the intrinsic was not called in release version due to `assert`.

**Comment by CarterLi** [comment]
You're correct thanks.
A question: Why do you [disable](https://github.com/cppformat/cppformat/blob/master/format.h#L584) ```count_digits(uint32_t n)``` conditionally when ```FMT_BUILTIN_CLZLL``` is not avaliable? I think ```count_digits(uint32_t n)``` can coexist with the fallback version of count_digits perfectly since ```count_digits(uint32_t n)``` is only an optimization in my opinion.
Note: ```_BitScanReverse64``` is only avaliable on __WIN64__. Provide ```count_digits(uint32_t n)``` should provide much better performance when compiling 32bit version.
In addition, we may implement ```__builtin_ctzll``` using ```__builtin_ctz``` when ```__builtin_ctzll``` when ```__builtin_ctzll``` is not avaliable ([for example](http://llvm.org/viewvc/llvm-project/libcxx/trunk/include/support/win32/support.h?view=markup#l134)), since 64bit operation is much more slower than 32bit operation on x86 and int (ie int32_t) is much more widely used than long long (ie int64_t).

**Comment by vitaut** [comment]
> Why do you disable count_digits(uint32_t n) conditionally when FMT_BUILTIN_CLZLL is not avaliable?

Good point, there is no reason to disable optimized `count_digits(uint32_t n)` when `FMT_BUILTIN_CLZLL` is not avaliable. I've fixed this in https://github.com/cppformat/cppformat/commit/cbc46d9e78f6935b83ca233f6f2c2fff533ab1ef.

As for implementing `__builtin_clzll` in terms of `__builtin_clz` on 32-bit platforms, this is reasonable although not critical, because, as you mentioned yourself, `int` is much more widely used than `long long` and `int` is already optimized on 32-bit platforms. Besides, 32-bit systems are becoming increasingly rare. But patches are welcome =).

**Comment by CarterLi** [comment]
well, what I want to say is that we only provide count_digits(uint64_t n) when __builtin_clz(ll) is not available, which means: if we call count_digits with an int on 32bit platform, we convert it into 64bit long long, do 64bit divisions

**Comment by vitaut** [comment]
Right, but `__builtin_clz` or equivalent should be available on most platforms. Do you know any popular platform where `__builtin_clz` is not provided? Not that I'm completely opposed to adding a fallback `count_digits(uint32_t)` variant (perhaps, by making `count_digits` a template), just want to make sure that we don't add anything that is almost never used.

**Comment by patlecat** [comment]
Ah I didn't know you're were using intrinsics already for GCC, RapidJson is also big on SSE usage to speed up their lib. MSVC coverage is very welcome. Cool :D

**Comment by patlecat** [comment]
Here is a way to check which intrinsics are available for MSVC (in case you don't know already):
https://msdn.microsoft.com/en-us/library/hskdteyh.aspx

**Comment by CarterLi** [comment]
According to the [Intel Instruction Set page](http://web.itu.edu.tr/kesgin/mul06/intel/instr/bsr.html), Bit Scan Reverse (BSR) is supported on i386+, should be supported in all modern CPUs.
Runtime CPUID check may not be used in this case since CPUID check itself takes time

**Comment by vitaut** [comment]
I agree with @CarterLi that it's better to avoid runtime checks, but thanks for the suggestion @patlecat. I was thinking of adding SSE support, but it [adds very little in terms of performance](https://github.com/miloyip/itoa-benchmark#results) while making implementation much more complicated.

**Comment by patlecat** [comment]
@vitaut  Then why did @miloyip rely on SSE for RapidJson?

You have a library here, so leave it to the developer on what nifty features to enable for his project, then you don't need CPUID, or offer a CPUID tool seperately to make the decision easier for your users.

**Comment by vitaut** [comment]
@patlecat Maybe I'm missing something, but it looks like RapidJson is not using SSE for integer to string conversion: https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/internal/itoa.h

Anyway, patches are welcome =)

**Comment by miloyip** [comment]
Yes, @vitaut . From my implementations, SSE2 does not improve the performance much in integer-to-string conversion so I didn't put that in RapidJSON. However, RapidJSON got performance boost by using SSE2/4 for skipping whitespaces during parsing. It also uses bit scan intrinsics in Grisu implementation (float-to-string conversion) as well.

RapidJSON does not use dynamic dispatching according to CPUID. It simply uses static binding. Some discussions about this can be found [here](https://code.google.com/p/rapidjson/issues/detail?id=53).

**Comment by vitaut** [comment]
Thanks, @miloyip, that's what I thought. You've done a great job with RapidJSON BTW.

**Pull request merged**
