### PR TITLE
Support named arguments

### PR DESCRIPTION
**Pull request by jamboree**
A squashed one.

### CODE REVIEW

**Comment by vitaut** [comment]
Merged, thanks for working on this!

**Comment by vitaut** [comment]
I also made a few somewhat opinionated but mostly minor changes in https://github.com/cppformat/cppformat/commit/4325c155f73b5844ac8f7973cfc1ec2bef2d7116 and https://github.com/cppformat/cppformat/commit/a98583dde3dde531d56c5f37db43c8c4be1aa9e0.

**Comment by vitaut** [comment]
@jamboree, could you please review the updated [CONTIBUTING](https://github.com/fmtlib/fmt/blob/ebec00138bd10e949ff34955bcb096387cd32acc/CONTRIBUTING.md) document, particularly the part about licensing, and let me know if you agree with it being applied both to your contributions to {fmt}? The library is likely to be relicensed (#1073) so I'm collecting approval from all earlier contributors. Thanks!

**Comment by jamboree** [comment]
No objections. 👍

**Pull request merged**
