### PR TITLE
fix compile warnings for Xcode

### PR DESCRIPTION
**Pull request by dixlorenz**
for me issue #96 is resolved with these changes, no more warnings

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR, but unfortunately it breaks the OS X release build: https://travis-ci.org/cppformat/cppformat/jobs/49730384.

**Comment by dixlorenz** [comment]
It seems it simply doesn't recognise the attribute; I am using "Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)", I would assume "AppleClang 6.0.0.6000054" is newer. I cannot reproduce the compile error; the only idea I have is to take out the attribute and just turn off the warning...

**Comment by vitaut** [comment]
I've merged your fixes for the documentation and return-after-throw warnings as separate commits https://github.com/cppformat/cppformat/commit/45d70b71ec227698fa92e1d6fb2f29f77af4fb93 and https://github.com/cppformat/cppformat/commit/37ad436068595a0722331510c8bfdf51c6df5749. Signed/unsigned comparison warning was fixed a bit earlier in https://github.com/cppformat/cppformat/commit/59254410daed335ba1e267a4606e666cf4a68391. The issue with `[[clang::fallthrough]]` needs further investigation though.
Thanks!

**Comment by dixlorenz** [comment]
Thanks for the merge; about the fallthrough, the easy way would be

# pragma clang diagnostic ignored "-Wimplicit-fallthrough"

**Comment by vitaut** [comment]
I think the `fallthrough` attribute is kind of nice, so I tried detecting it with [__has_cpp_attribute](http://clang.llvm.org/docs/LanguageExtensions.html#has-cpp-attribute) in https://github.com/cppformat/cppformat/commit/d7fea1ba0c387be568236fc4bd5e945eaa0145ae. Hope it works for you, otherwise feel free to (re)open an issue or PR.

**Comment by dixlorenz** [comment]
I do prefer the attribute way too, this compiles for me but the warning is back; took me a bit to figure it out, __has_cpp_attribute has only been added to clang on 11/14/2014:

http://blog.llvm.org/2014/11/llvm-weekly-46-nov-17th-2014.html
http://reviews.llvm.org/rL221991 

The fix will probably work with the next version of Xcode (assuming that's based on clang 3.6), but not with the current one.

**Pull request closed without merging**
